# Generated by Django 4.1.9 on 2023-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algebra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="latex",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
