# Generated by Django 4.1.9 on 2023-06-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("algebra", "0002_alter_expression_latex"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckSolution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("expr1_latex", models.CharField(blank=True, max_length=100, null=True)),
                ("did_expr1_subst", models.BooleanField(default=False)),
                ("expr2_latex", models.CharField(blank=True, max_length=100, null=True)),
                ("substitution_values", models.JSONField(null=True)),
                ("solving_for", models.CharField(blank=True, max_length=100, null=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("attempt", models.CharField(blank=True, max_length=100, null=True)),
                ("problem_solved", models.BooleanField(default=False)),
                (
                    "expr1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_expr1",
                        to="algebra.expression",
                    ),
                ),
                (
                    "expr2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_expr2",
                        to="algebra.expression",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_problem",
                        to="algebra.problem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CheckRewrite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("expr1_latex", models.CharField(blank=True, max_length=100, null=True)),
                ("did_expr1_subst", models.BooleanField(default=False)),
                ("expr2_latex", models.CharField(blank=True, max_length=100, null=True)),
                ("substitution_values", models.JSONField(null=True)),
                ("solving_for", models.CharField(blank=True, max_length=100, null=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("are_equivalent", models.BooleanField(default=False)),
                (
                    "expr1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_expr1",
                        to="algebra.expression",
                    ),
                ),
                (
                    "expr2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_expr2",
                        to="algebra.expression",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_problem",
                        to="algebra.problem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
