# Generated by Django 4.1.9 on 2023-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algebra", "0003_checksolution_checkrewrite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkrewrite",
            name="are_equivalent",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
