# Generated by Django 4.1.9 on 2023-06-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algebra", "0005_alter_step_left_expr_alter_step_right_expr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkrewrite",
            name="substitution_values",
        ),
        migrations.RemoveField(
            model_name="checksolution",
            name="substitution_values",
        ),
        migrations.AddField(
            model_name="checkrewrite",
            name="other_var",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="checkrewrite",
            name="other_var_value",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkrewrite",
            name="solving_for_value",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checksolution",
            name="other_var",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="checksolution",
            name="other_var_value",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checksolution",
            name="solving_for_value",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
