# Generated by Django 4.1.9 on 2023-06-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algebra", "0006_remove_checkrewrite_substitution_values_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkrewrite",
            name="other_var_value",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="checkrewrite",
            name="solving_for_value",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="checksolution",
            name="other_var_value",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="checksolution",
            name="solving_for_value",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
