# Generated by Django 4.1.9 on 2023-06-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algebra", "0007_alter_checkrewrite_other_var_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checksolution",
            name="problem_solved",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
