# Generated by Django 4.1.9 on 2023-06-26 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("algebra", "0008_alter_checksolution_problem_solved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checksolution",
            name="problem_solved",
        ),
    ]
