# Generated by Django 4.1.9 on 2023-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algebra", "0009_remove_checksolution_problem_solved"),
    ]

    operations = [
        migrations.AddField(
            model_name="checksolution",
            name="problem_solved",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
