# Generated by Django 4.1.9 on 2023-08-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algebra", "0012_alter_checksolution_problem_solved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checksolution",
            name="problem_solved",
            field=models.CharField(
                choices=[
                    ("solved", "The problem has one answer."),
                    ("inf many", "The problem has infinitely many answers."),
                    ("no solution", "The problem does not have an answer."),
                    ("unsolved", "The problem is not solved yet."),
                    ("incomplete", "The solution check was not completed."),
                ],
                default="incomplete",
                max_length=11,
            ),
        ),
    ]
