# Generated by Django 4.1.9 on 2023-09-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algebra", "0013_alter_checksolution_problem_solved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkrewrite",
            name="other_var_value",
        ),
        migrations.RemoveField(
            model_name="checkrewrite",
            name="solving_for_value",
        ),
        migrations.RemoveField(
            model_name="checksolution",
            name="other_var_value",
        ),
        migrations.RemoveField(
            model_name="checksolution",
            name="solving_for_value",
        ),
        migrations.AddField(
            model_name="checkrewrite",
            name="other_var_value_expr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="checkrewrite",
            name="solving_for_value_expr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="checksolution",
            name="other_var_value_expr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="checksolution",
            name="solving_for_value_expr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
