# Generated by Django 4.1.9 on 2023-11-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("algebra", "0015_rename_other_var_value_expr_checkrewrite_other_var_latex_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="problem",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, related_name="step", to="algebra.problem"
            ),
        ),
    ]
