# Generated by Django 4.1.9 on 2023-06-07 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sandbox",
                    models.CharField(
                        choices=[
                            ("Prealgebra", "Pre-algebra"),
                            ("Algebra", "Algebra"),
                            ("Graphs", "Graphs"),
                            ("Shapes", "Shapes"),
                        ],
                        default="Algebra",
                        max_length=10,
                    ),
                ),
                ("problem_id", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("choose-rewrite-values", "Choosing rewrite values"),
                            (
                                "choose-solution-values",
                                "Choosing solution values (when solving for one variable in terms of another",
                            ),
                            ("check-rewrite", "Checking rewrite"),
                            ("check-solution", "Checking solution"),
                            ("no-context", "No context"),
                        ],
                        default="no-context",
                        max_length=25,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message",
                        to="calculator.usermessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_type",
                    models.CharField(choices=[("latex", "LaTex"), ("text", "Text")], default="text", max_length=5),
                ),
                ("content", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "response_message",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_message",
                        to="calculator.response",
                    ),
                ),
                (
                    "user_message",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_message",
                        to="calculator.usermessage",
                    ),
                ),
            ],
        ),
    ]
