# Generated by Django 4.1.9 on 2023-06-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0002_alter_content_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                choices=[("latex", "LaTex"), ("text", "Text"), ("hidden", "Hidden")], default="text", max_length=6
            ),
        ),
    ]
