# Generated by Django 4.1.9 on 2023-08-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_mistake_mistake_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mistake",
            name="is_fixed",
            field=models.BooleanField(default=False),
        ),
    ]
