# Generated by Django 4.1.9 on 2023-09-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_mistake_is_fixed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proceed",
            name="proceed_type",
            field=models.CharField(
                choices=[("add step", "User attempted to add new step to the problem")], default=None, max_length=15
            ),
        ),
    ]
