# Generated by Django 4.1.9 on 2023-11-05 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_mistake_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mistake",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="owner", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
