# Generated by Django 4.1.9 on 2023-11-05 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_mistake_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpclick",
            name="clicker",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proceed",
            name="solver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
