# Generated by Django 4.1.9 on 2023-11-05 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_helpclick_clicker_proceed_solver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helpclick",
            name="clicker",
        ),
        migrations.RemoveField(
            model_name="proceed",
            name="solver",
        ),
    ]
